// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	entity "todo-togo/entity"

	mock "github.com/stretchr/testify/mock"
)

// IStatusRepo is an autogenerated mock type for the IStatusRepo type
type IStatusRepo struct {
	mock.Mock
}

// SelectAllStatus provides a mock function with given fields:
func (_m *IStatusRepo) SelectAllStatus() ([]entity.Status, error) {
	ret := _m.Called()

	var r0 []entity.Status
	if rf, ok := ret.Get(0).(func() []entity.Status); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Status)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
